version: "3"

services:
  mongodb:
    image: mongo:5.0-focal
    container_name: mongodb
    # Use credential given in .env file in the project root
    environment:
        # - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
        - MONGO_INITDB_ROOT_USERNAME=username
        # - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
        - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod